openapi: 3.0.0
info:
  title: flask_api
  description: ml_api
  version: 0.0.0

servers:
  - url: http://0.0.0.0:5000

paths:
  /predict:
    post:
      summary: "予測結果"
      description: "予測結果を返します"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                feature:
                  type: object
                  properties:
                    age:
                      type: integer
      responses:
        '200':
          description: "予測成功"
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: integer
